name: price_q_r
description: Lector de precio QR

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: ^3.4.1
  cached_network_image_platform_interface: 4.1.1
  cached_network_image_web: 1.3.1
  collection: 1.19.1
  dropdown_button2: 2.3.9
  flutter_animate: ^4.5.2
  flutter_cache_manager: 3.4.1
  flutter_keyboard_visibility: 
    git:
      url: https://github.com/FlutterFlow/flutter_keyboard_visibility.git
      path: flutter_keyboard_visibility
      ref: b39c1d0ca1671458e4daf3eea2ebe11741f9bcf3
  flutter_keyboard_visibility_linux: 1.0.0
  flutter_keyboard_visibility_macos: 1.0.0
  flutter_keyboard_visibility_platform_interface: 2.0.0
  flutter_keyboard_visibility_web: 
    git:
      url: https://github.com/FlutterFlow/flutter_keyboard_visibility.git
      path: flutter_keyboard_visibility_web
      ref: b39c1d0ca1671458e4daf3eea2ebe11741f9bcf3
  flutter_keyboard_visibility_windows: 1.0.0
  font_awesome_flutter: ^10.12.0
  from_css_color: 2.0.0
  go_router: ^16.3.0
  google_fonts: ^6.3.2
  intl: 0.20.2
  json_path: ^0.8.0
  page_transition: ^2.2.1
  path_provider: ^2.1.5
  path_provider_android: ^2.2.20
  path_provider_foundation: ^2.4.3
  path_provider_linux: 2.2.1
  path_provider_platform_interface: 2.1.2
  path_provider_windows: 2.3.0
  provider: ^6.1.5+1
  shared_preferences: 2.5.3
  shared_preferences_android: ^2.4.15
  shared_preferences_foundation: ^2.5.5
  shared_preferences_linux: 2.4.1
  shared_preferences_platform_interface: 2.4.1
  shared_preferences_web: 2.4.3
  shared_preferences_windows: 2.4.1
  sqflite: ^2.4.2
  sqflite_common: ^2.5.6
  timeago: 3.7.1
  url_launcher: ^6.3.2
  url_launcher_android: ^6.3.24
  url_launcher_ios: ^6.3.5
  url_launcher_linux: 3.2.1
  url_launcher_macos: ^3.2.4
  url_launcher_platform_interface: 2.3.2
  url_launcher_web: 2.4.1
  url_launcher_windows: 3.1.4
  mobile_scanner: ^7.1.2

  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.2
  firebase_auth: ^5.3.3
  firebase_storage: ^12.3.4
  image_picker: ^1.2.0
  image: ^4.5.4
  qr_flutter: ^4.1.0
  
  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  http: ^1.4.0

dependency_overrides:
  http: 1.4.0
  uuid: ^4.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  
  lints: ^6.0.0
  flutter_test:
    sdk: flutter


flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  web:
    generate: true
  image_path: 'assets/images/app_launcher_icon.png'
  adaptive_icon_background: '#00000000'
  adaptive_icon_foreground: 'assets/images/adaptive_foreground_icon.png'


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/

  fonts:
    - family: GatedCommunity
      fonts:
        - asset: assets/fonts/Gated-Community.ttf


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

