// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
       return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
  apiKey: 'AIzaSyAo_920ObGG6eOLvCPdR5U7fmtC6XxD2K0',
  appId: '1:968736313295:android:57149b581a36219b4e0cba',
  messagingSenderId: '968736313295',
  projectId: 'priceqr',
  storageBucket: 'priceqr.firebasestorage.app',
);


  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxSw6sP2ho6LMFrf-GFeQ29pSnpoSNsAY',
    appId: '1:968736313295:web:3f14104e7cf397cf4e0cba',
    messagingSenderId: '968736313295',
    projectId: 'priceqr',
    authDomain: 'priceqr.firebaseapp.com',
    storageBucket: 'priceqr.firebasestorage.app',
    measurementId: 'G-PYJX6EZLPH',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8nufeXTbIeznrtJPQ_OaWzSVjdux3x1g',
    appId: '1:968736313295:ios:af0c0707832d4b184e0cba',
    messagingSenderId: '968736313295',
    projectId: 'priceqr',
    storageBucket: 'priceqr.firebasestorage.app',
    iosBundleId: 'com.SynergyLabs.gatedcommunity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8nufeXTbIeznrtJPQ_OaWzSVjdux3x1g',
    appId: '1:968736313295:ios:01b1c4db21133abd4e0cba',
    messagingSenderId: '968736313295',
    projectId: 'priceqr',
    storageBucket: 'priceqr.firebasestorage.app',
    iosBundleId: 'com.synergylabs.priceqr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxSw6sP2ho6LMFrf-GFeQ29pSnpoSNsAY',
    appId: '1:968736313295:web:d76554625f91029d4e0cba',
    messagingSenderId: '968736313295',
    projectId: 'priceqr',
    authDomain: 'priceqr.firebaseapp.com',
    storageBucket: 'priceqr.firebasestorage.app',
    measurementId: 'G-8CDSPMVSN6',
  );
}
